services:
  server:
    build:
      context: .
      target: server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  client:
    build:
      context: .
      target: client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - server
